### ISSUE TITLE
Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?

### ISSUE THREAD

**Issue by eljejer** [jotta/jotta-cli-issues#133]
Make sure you are running the latest version of jotta-cli before reporting an issue.

**jotta-cli release (`jotta-cli version`):**
jotta-cli-0.9.39536
**Description of problem:**
jottad keeps stopping after initiating a download 
**Expected:**
jottad keep on running

**jotta-cli status (`jotta-cli status`):**
```
Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?
```

**Relevant logs for the issue (`~/.jottad/jottabackup.log or /var/lib/jotta/jottabackup.log ` )**
```
pid:19641 2021/02/20 22:58:14 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:19641 2021/02/20 22:58:14 jottad.init
pid:19641 2021/02/20 22:58:14 jottad.init.appdata => /var/lib/jottad
pid:19641 2021/02/20 22:58:14 jottad.appdata    /var/lib/jottad
pid:19641 2021/02/20 22:58:14 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858294|264)
pid:19641 2021/02/20 22:58:14 Error loading existing session on auth.New loadsession: not found
pid:19641 2021/02/20 22:58:14 localfiles.init => 1.1.0
pid:19641 2021/02/20 22:58:14 jottad.init.cfg.downloadrate => 0B/s
pid:19641 2021/02/20 22:58:14 jottad.init.cfg.uploadrate => 0B/s
pid:19641 2021/02/20 22:58:14 jottad.init.user => no user logged in
pid:19641 2021/02/20 22:58:14 jottad.init.cfg.scaninterval =>  1h0m0s
pid:19641 2021/02/20 22:58:14 jottad.init.done => ok
pid:19641 2021/02/20 22:58:14 jottad.startup
pid:19641 2021/02/20 22:58:14 jottad.startup.auth.patch
pid:19641 2021/02/20 22:58:14 api.grpc.tls.active => 127.0.0.1:14443
pid:19641 2021/02/20 22:58:16 jottad.startup => ok
pid:19641 2021/02/20 22:58:16 GET https://repo.jotta.us/archives/VERSION 200
pid:19641 2021/02/20 22:59:47 ===========
pid:19641 2021/02/20 22:59:47 Logging in
pid:19641 2021/02/20 22:59:48 login.session.ok
pid:19641 2021/02/20 22:59:48 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:19641 2021/02/20 22:59:48 ===========
pid:19641 2021/02/20 22:59:51 jottad.created-device => VEBODROID
pid:19641 2021/02/20 23:04:09 Attempting download of /archive/Pictures_27062015/Pictures/1 Zeer divers
pid:19641 2021/02/20 23:04:09 Unable to start download: Destination path [/mnt/WD/Pictures_jottacloud] is not writable by jottad running as:jottad
pid:19641 2021/02/20 23:05:18 Attempting download of /archive/Pictures_27062015/Pictures/1 Zeer divers
pid:19641 2021/02/20 23:05:18 Download starting: /archive/Pictures_27062015/Pictures/1 Zeer divers (isfile:false)=> /mnt/WD/Pictures_jottacloud/1 Zeer divers
pid:19641 2021/02/20 23:05:26 Found 40 folders 2133 files (5.60GiB) in 7.973989171s
pid:19641 2021/02/20 23:05:26 Download queued: /archive/Pictures_27062015/Pictures/1 Zeer divers => /mnt/WD/Pictures_jottacloud/1 Zeer divers == cf53ec6dab
pid:19641 2021/02/20 23:05:26 Download cf53ec6dab started 2133 files
pid:19919 2021/02/20 23:05:26 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:19919 2021/02/20 23:05:26 jottad.init
pid:19919 2021/02/20 23:05:26 jottad.init.appdata => /var/lib/jottad
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/db (1613858391|32768)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/downloads
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858726|32768)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858726|3327)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/localfiles (1613858718|32768)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/obj
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:19919 2021/02/20 23:05:26 jottad.appdata    /var/lib/jottad/settings.dat (1613858294|421)
pid:19919 2021/02/20 23:05:26 updating backup DB from version 0 to 1
pid:19919 2021/02/20 23:05:26 Loading settings from /var/lib/jottad/settings.dat
pid:19919 2021/02/20 23:05:27 jottad.init.cfg.downloadrate => 0B/s
pid:19919 2021/02/20 23:05:27 jottad.init.cfg.uploadrate => 0B/s
pid:19919 2021/02/20 23:05:27 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:19919 2021/02/20 23:05:27 jottad.init.cfg.scaninterval =>  1h0m0s
pid:19919 2021/02/20 23:05:27 jottad.init.done => ok
pid:19919 2021/02/20 23:05:27 jottad.startup
pid:19919 2021/02/20 23:05:27 api.grpc.tls.active => 127.0.0.1:14443
pid:19919 2021/02/20 23:05:27 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:19919 2021/02/20 23:05:27 jottad.startup.confirm-remote => ok
pid:19919 2021/02/20 23:05:27 jottad.startup => ok
pid:19919 2021/02/20 23:05:27 Download cf53ec6dab started 2133 files
pid:19939 2021/02/20 23:05:27 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:19939 2021/02/20 23:05:27 jottad.init
pid:19939 2021/02/20 23:05:27 jottad.init.appdata => /var/lib/jottad
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/db (1613858727|32768)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/downloads
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858727|32768)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858727|5838)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/localfiles (1613858727|32768)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/obj
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/settings.dat (1613858727|421)
pid:19939 2021/02/20 23:05:27 jottad.appdata    /var/lib/jottad/store - (27232b407ae588d9cd52c68c3878da61|1613858727|254)
pid:19939 2021/02/20 23:05:27 Loading settings from /var/lib/jottad/settings.dat
pid:19939 2021/02/20 23:05:28 jottad.init.cfg.downloadrate => 0B/s
pid:19939 2021/02/20 23:05:28 jottad.init.cfg.uploadrate => 0B/s
pid:19939 2021/02/20 23:05:28 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:19939 2021/02/20 23:05:28 jottad.init.cfg.scaninterval =>  1h0m0s
pid:19939 2021/02/20 23:05:28 jottad.init.done => ok
pid:19939 2021/02/20 23:05:28 jottad.startup
pid:19939 2021/02/20 23:05:28 api.grpc.tls.active => 127.0.0.1:14443
pid:19939 2021/02/20 23:05:28 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:19939 2021/02/20 23:05:28 jottad.startup.confirm-remote => ok
pid:19939 2021/02/20 23:05:28 jottad.startup => ok
pid:19939 2021/02/20 23:05:28 Download cf53ec6dab started 2133 files
pid:19958 2021/02/20 23:05:28 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:19958 2021/02/20 23:05:28 jottad.init
pid:19958 2021/02/20 23:05:28 jottad.init.appdata => /var/lib/jottad
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/db (1613858728|32768)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/downloads
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858728|32768)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858728|8399)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/localfiles (1613858728|32768)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/obj
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:19958 2021/02/20 23:05:28 jottad.appdata    /var/lib/jottad/settings.dat (1613858728|421)
pid:19958 2021/02/20 23:05:28 Loading settings from /var/lib/jottad/settings.dat
pid:19958 2021/02/20 23:05:29 jottad.init.cfg.downloadrate => 0B/s
pid:19958 2021/02/20 23:05:29 jottad.init.cfg.uploadrate => 0B/s
pid:19958 2021/02/20 23:05:29 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:19958 2021/02/20 23:05:29 jottad.init.cfg.scaninterval =>  1h0m0s
pid:19958 2021/02/20 23:05:29 jottad.init.done => ok
pid:19958 2021/02/20 23:05:29 jottad.startup
pid:19958 2021/02/20 23:05:29 api.grpc.tls.active => 127.0.0.1:14443
pid:19958 2021/02/20 23:05:29 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:19958 2021/02/20 23:05:29 jottad.startup.confirm-remote => ok
pid:19958 2021/02/20 23:05:29 jottad.startup => ok
pid:19958 2021/02/20 23:05:29 Download cf53ec6dab started 2133 files
pid:19978 2021/02/20 23:05:29 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:19978 2021/02/20 23:05:29 jottad.init
pid:19978 2021/02/20 23:05:29 jottad.init.appdata => /var/lib/jottad
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/db (1613858729|32768)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/downloads
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858729|32768)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858729|10841)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/localfiles (1613858729|32768)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/obj
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/settings.dat (1613858729|421)
pid:19978 2021/02/20 23:05:29 jottad.appdata    /var/lib/jottad/store - (696248a77a38896aa8ec2908a58cde60|1613858729|254)
pid:19978 2021/02/20 23:05:29 Loading settings from /var/lib/jottad/settings.dat
pid:19978 2021/02/20 23:05:30 jottad.init.cfg.downloadrate => 0B/s
pid:19978 2021/02/20 23:05:30 jottad.init.cfg.uploadrate => 0B/s
pid:19978 2021/02/20 23:05:30 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:19978 2021/02/20 23:05:30 jottad.init.cfg.scaninterval =>  1h0m0s
pid:19978 2021/02/20 23:05:30 jottad.init.done => ok
pid:19978 2021/02/20 23:05:30 jottad.startup
pid:19978 2021/02/20 23:05:30 api.grpc.tls.active => 127.0.0.1:14443
pid:19978 2021/02/20 23:05:30 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:19978 2021/02/20 23:05:30 jottad.startup.confirm-remote => ok
pid:19978 2021/02/20 23:05:30 jottad.startup => ok
pid:19978 2021/02/20 23:05:30 Download cf53ec6dab started 2133 files
pid:19998 2021/02/20 23:05:30 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:19998 2021/02/20 23:05:30 jottad.init
pid:19998 2021/02/20 23:05:30 jottad.init.appdata => /var/lib/jottad
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/db (1613858730|32768)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/downloads
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858730|32768)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858730|13403)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/localfiles (1613858730|32768)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/obj
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:19998 2021/02/20 23:05:30 jottad.appdata    /var/lib/jottad/settings.dat (1613858730|421)
pid:19998 2021/02/20 23:05:30 Loading settings from /var/lib/jottad/settings.dat
pid:19998 2021/02/20 23:05:31 jottad.init.cfg.downloadrate => 0B/s
pid:19998 2021/02/20 23:05:31 jottad.init.cfg.uploadrate => 0B/s
pid:19998 2021/02/20 23:05:31 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:19998 2021/02/20 23:05:31 jottad.init.cfg.scaninterval =>  1h0m0s
pid:19998 2021/02/20 23:05:31 jottad.init.done => ok
pid:19998 2021/02/20 23:05:31 jottad.startup
pid:19998 2021/02/20 23:05:31 api.grpc.tls.active => 127.0.0.1:14443
pid:19998 2021/02/20 23:05:31 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:19998 2021/02/20 23:05:31 jottad.startup.confirm-remote => ok
pid:19998 2021/02/20 23:05:31 jottad.startup => ok
pid:19998 2021/02/20 23:05:31 Download cf53ec6dab started 2133 files
pid:20092 2021/02/20 23:07:10 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:20092 2021/02/20 23:07:10 jottad.init
pid:20092 2021/02/20 23:07:10 jottad.init.appdata => /var/lib/jottad
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/db (1613858731|32768)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/downloads
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858731|32768)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858830|15846)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/localfiles (1613858731|32768)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/obj
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:20092 2021/02/20 23:07:10 jottad.appdata    /var/lib/jottad/settings.dat (1613858731|421)
pid:20092 2021/02/20 23:07:10 Loading settings from /var/lib/jottad/settings.dat
pid:20092 2021/02/20 23:07:10 jottad.init.cfg.downloadrate => 0B/s
pid:20092 2021/02/20 23:07:10 jottad.init.cfg.uploadrate => 0B/s
pid:20092 2021/02/20 23:07:10 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:20092 2021/02/20 23:07:10 jottad.init.cfg.scaninterval =>  1h0m0s
pid:20092 2021/02/20 23:07:10 jottad.init.done => ok
pid:20092 2021/02/20 23:07:10 jottad.startup
pid:20092 2021/02/20 23:07:10 api.grpc.tls.active => 127.0.0.1:14443
pid:20092 2021/02/20 23:07:10 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:20092 2021/02/20 23:07:10 jottad.startup.confirm-remote => ok
pid:20092 2021/02/20 23:07:10 jottad.startup => ok
pid:20092 2021/02/20 23:07:10 Download cf53ec6dab started 2133 files
pid:20111 2021/02/20 23:07:11 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:20111 2021/02/20 23:07:11 jottad.init
pid:20111 2021/02/20 23:07:11 jottad.init.appdata => /var/lib/jottad
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/db (1613858830|32768)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/downloads
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858830|32768)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858831|18289)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/localfiles (1613858830|32768)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/obj
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/settings.dat (1613858830|421)
pid:20111 2021/02/20 23:07:11 jottad.appdata    /var/lib/jottad/store - (4dd124094648872d006903e4caec4218|1613858830|254)
pid:20111 2021/02/20 23:07:11 Loading settings from /var/lib/jottad/settings.dat
pid:20111 2021/02/20 23:07:11 jottad.init.cfg.downloadrate => 0B/s
pid:20111 2021/02/20 23:07:11 jottad.init.cfg.uploadrate => 0B/s
pid:20111 2021/02/20 23:07:11 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:20111 2021/02/20 23:07:11 jottad.init.cfg.scaninterval =>  1h0m0s
pid:20111 2021/02/20 23:07:11 jottad.init.done => ok
pid:20111 2021/02/20 23:07:11 jottad.startup
pid:20111 2021/02/20 23:07:11 api.grpc.tls.active => 127.0.0.1:14443
pid:20111 2021/02/20 23:07:11 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:20111 2021/02/20 23:07:11 jottad.startup.confirm-remote => ok
pid:20111 2021/02/20 23:07:11 jottad.startup => ok
pid:20111 2021/02/20 23:07:11 Download cf53ec6dab started 2133 files
pid:20128 2021/02/20 23:07:12 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:20128 2021/02/20 23:07:12 jottad.init
pid:20128 2021/02/20 23:07:12 jottad.init.appdata => /var/lib/jottad
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/db (1613858831|32768)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/downloads
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858831|32768)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858832|20851)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/localfiles (1613858831|32768)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/obj
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:20128 2021/02/20 23:07:12 jottad.appdata    /var/lib/jottad/settings.dat (1613858831|421)
pid:20128 2021/02/20 23:07:12 Loading settings from /var/lib/jottad/settings.dat
pid:20128 2021/02/20 23:07:12 jottad.init.cfg.downloadrate => 0B/s
pid:20128 2021/02/20 23:07:12 jottad.init.cfg.uploadrate => 0B/s
pid:20128 2021/02/20 23:07:12 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:20128 2021/02/20 23:07:12 jottad.init.cfg.scaninterval =>  1h0m0s
pid:20128 2021/02/20 23:07:12 jottad.init.done => ok
pid:20128 2021/02/20 23:07:12 jottad.startup
pid:20128 2021/02/20 23:07:12 api.grpc.tls.active => 127.0.0.1:14443
pid:20128 2021/02/20 23:07:12 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:20128 2021/02/20 23:07:12 jottad.startup.confirm-remote => ok
pid:20128 2021/02/20 23:07:12 jottad.startup => ok
pid:20128 2021/02/20 23:07:12 Download cf53ec6dab started 2133 files
pid:20146 2021/02/20 23:07:13 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:20146 2021/02/20 23:07:13 jottad.init
pid:20146 2021/02/20 23:07:13 jottad.init.appdata => /var/lib/jottad
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/db (1613858832|32768)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/downloads
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858832|32768)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858833|23294)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/localfiles (1613858832|32768)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/obj
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/settings.dat (1613858832|421)
pid:20146 2021/02/20 23:07:13 jottad.appdata    /var/lib/jottad/store - (140b966c9fb8c9d48ca984e70ae34f63|1613858832|254)
pid:20146 2021/02/20 23:07:13 Loading settings from /var/lib/jottad/settings.dat
pid:20146 2021/02/20 23:07:13 jottad.init.cfg.downloadrate => 0B/s
pid:20146 2021/02/20 23:07:13 jottad.init.cfg.uploadrate => 0B/s
pid:20146 2021/02/20 23:07:13 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:20146 2021/02/20 23:07:13 jottad.init.cfg.scaninterval =>  1h0m0s
pid:20146 2021/02/20 23:07:13 jottad.init.done => ok
pid:20146 2021/02/20 23:07:13 jottad.startup
pid:20146 2021/02/20 23:07:13 api.grpc.tls.active => 127.0.0.1:14443
pid:20146 2021/02/20 23:07:13 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:20146 2021/02/20 23:07:13 jottad.startup.confirm-remote => ok
pid:20146 2021/02/20 23:07:13 jottad.startup => ok
pid:20146 2021/02/20 23:07:13 Download cf53ec6dab started 2133 files
pid:20166 2021/02/20 23:07:14 Starting /usr/bin/jottad version 0.9.39536 as 966(jottad)/966
pid:20166 2021/02/20 23:07:14 jottad.init
pid:20166 2021/02/20 23:07:14 jottad.init.appdata => /var/lib/jottad
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/.ignore (1613858294|490)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/db (1613858833|32768)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/downloads
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/failed (1613858718|32768)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/index (1613858833|32768)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/downloads/cf53ec6dab/queued (1613858726|4194304)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/downloads/history (1613858294|16384)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/jottabackup.log (1613858834|25856)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/localfiles (1613858833|32768)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/nstore - (4585c969d0a94dc93bb9f71a419f1e8b|1613858388|65536)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/obj
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/obj/5b296082 (1613858401|813)
pid:20166 2021/02/20 23:07:14 jottad.appdata    /var/lib/jottad/settings.dat (1613858833|421)
pid:20166 2021/02/20 23:07:14 Loading settings from /var/lib/jottad/settings.dat
pid:20166 2021/02/20 23:07:14 jottad.init.cfg.downloadrate => 0B/s
pid:20166 2021/02/20 23:07:14 jottad.init.cfg.uploadrate => 0B/s
pid:20166 2021/02/20 23:07:14 jottad.init.user => [lvbaal] on [VEBODROID] @ [8610e8f54ea5e87adba99ebb7bb00177]
pid:20166 2021/02/20 23:07:14 jottad.init.cfg.scaninterval =>  1h0m0s
pid:20166 2021/02/20 23:07:14 jottad.init.done => ok
pid:20166 2021/02/20 23:07:14 jottad.startup
pid:20166 2021/02/20 23:07:14 api.grpc.tls.active => 127.0.0.1:14443
pid:20166 2021/02/20 23:07:14 jottad.startup.update-userinfo => leovb+jottacloud@pm.me Jottacloud 8610e8f54ea5e87adba99ebb7bb00177
pid:20166 2021/02/20 23:07:14 jottad.startup.confirm-remote => ok
pid:20166 2021/02/20 23:07:14 jottad.startup => ok
pid:20166 2021/02/20 23:07:14 Download cf53ec6dab started 2133 files
```

**Traceback**
```
journalctl -u jottad -e

Feb 20 23:07:12 VEBODROID systemd[1]: Started Jottacloud cli.
Feb 20 23:07:12 VEBODROID jottad[20128]: [20128] creating logger @ /var/lib/jottad/jottabackup.log
Feb 20 23:07:12 VEBODROID jottad[20128]: Error parsing syslog info: section 'syslog' does not existpanic: runtime error: invalid memory address or nil pointer dereference
Feb 20 23:07:12 VEBODROID jottad[20128]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ffc]
Feb 20 23:07:12 VEBODROID jottad[20128]: goroutine 24 [running]:
Feb 20 23:07:12 VEBODROID jottad[20128]: runtime/internal/atomic.goLoad64(0x107828c, 0x1, 0x6)
Feb 20 23:07:12 VEBODROID jottad[20128]:         /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
Feb 20 23:07:12 VEBODROID jottad[20128]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*Download).shouldAbort(...)
Feb 20 23:07:12 VEBODROID jottad[20128]:         /builds/jotta/desktop/client/pkg/network/download/download.go:75
Feb 20 23:07:12 VEBODROID jottad[20128]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).startDownloading.func2(0x78e368)
Feb 20 23:07:12 VEBODROID jottad[20128]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:561 +0x8c
Feb 20 23:07:12 VEBODROID jottad[20128]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).startDownloading(0x13680c0, 0x1078270)
Feb 20 23:07:12 VEBODROID jottad[20128]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:585 +0x394
Feb 20 23:07:12 VEBODROID jottad[20128]: created by git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).pushQueue
Feb 20 23:07:12 VEBODROID jottad[20128]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:445 +0x60
Feb 20 23:07:12 VEBODROID systemd[1]: jottad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 20 23:07:12 VEBODROID systemd[1]: jottad.service: Failed with result 'exit-code'.
Feb 20 23:07:13 VEBODROID systemd[1]: jottad.service: Scheduled restart job, restart counter is at 3.
Feb 20 23:07:13 VEBODROID systemd[1]: Stopped Jottacloud cli.
Feb 20 23:07:13 VEBODROID systemd[1]: Started Jottacloud cli.
Feb 20 23:07:13 VEBODROID jottad[20146]: [20146] creating logger @ /var/lib/jottad/jottabackup.log
Feb 20 23:07:13 VEBODROID jottad[20146]: Error parsing syslog info: section 'syslog' does not existpanic: runtime error: invalid memory address or nil pointer dereference
Feb 20 23:07:13 VEBODROID jottad[20146]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ffc]
Feb 20 23:07:13 VEBODROID jottad[20146]: goroutine 98 [running]:
Feb 20 23:07:13 VEBODROID jottad[20146]: runtime/internal/atomic.goLoad64(0x13c810c, 0x1, 0x6)
Feb 20 23:07:13 VEBODROID jottad[20146]:         /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
Feb 20 23:07:13 VEBODROID jottad[20146]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*Download).shouldAbort(...)
Feb 20 23:07:13 VEBODROID jottad[20146]:         /builds/jotta/desktop/client/pkg/network/download/download.go:75
Feb 20 23:07:13 VEBODROID jottad[20146]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).startDownloading.func2(0x78e368)
Feb 20 23:07:13 VEBODROID jottad[20146]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:561 +0x8c
Feb 20 23:07:13 VEBODROID jottad[20146]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).startDownloading(0x1392720, 0x13c80f0)
Feb 20 23:07:13 VEBODROID jottad[20146]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:585 +0x394
Feb 20 23:07:13 VEBODROID jottad[20146]: created by git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).pushQueue
Feb 20 23:07:13 VEBODROID jottad[20146]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:445 +0x60
Feb 20 23:07:13 VEBODROID systemd[1]: jottad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 20 23:07:13 VEBODROID systemd[1]: jottad.service: Failed with result 'exit-code'.
Feb 20 23:07:14 VEBODROID systemd[1]: jottad.service: Scheduled restart job, restart counter is at 4.
Feb 20 23:07:14 VEBODROID systemd[1]: Stopped Jottacloud cli.
Feb 20 23:07:14 VEBODROID systemd[1]: Started Jottacloud cli.
Feb 20 23:07:14 VEBODROID jottad[20166]: [20166] creating logger @ /var/lib/jottad/jottabackup.log
Feb 20 23:07:14 VEBODROID jottad[20166]: Error parsing syslog info: section 'syslog' does not existpanic: runtime error: invalid memory address or nil pointer dereference
Feb 20 23:07:14 VEBODROID jottad[20166]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ffc]
Feb 20 23:07:14 VEBODROID jottad[20166]: goroutine 45 [running]:
Feb 20 23:07:14 VEBODROID jottad[20166]: runtime/internal/atomic.goLoad64(0x138058c, 0x1, 0x6)
Feb 20 23:07:14 VEBODROID jottad[20166]:         /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
Feb 20 23:07:14 VEBODROID jottad[20166]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*Download).shouldAbort(...)
Feb 20 23:07:14 VEBODROID jottad[20166]:         /builds/jotta/desktop/client/pkg/network/download/download.go:75
Feb 20 23:07:14 VEBODROID jottad[20166]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).startDownloading.func2(0x78e368)
Feb 20 23:07:14 VEBODROID jottad[20166]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:561 +0x8c
Feb 20 23:07:14 VEBODROID jottad[20166]: git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).startDownloading(0x137a120, 0x1380570)
Feb 20 23:07:14 VEBODROID jottad[20166]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:585 +0x394
Feb 20 23:07:14 VEBODROID jottad[20166]: created by git.jotta.us/jotta/desktop/client/pkg/network/download.(*DownloadManager).pushQueue
Feb 20 23:07:14 VEBODROID jottad[20166]:         /builds/jotta/desktop/client/pkg/network/download/downloader.go:445 +0x60
Feb 20 23:07:14 VEBODROID systemd[1]: jottad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 20 23:07:14 VEBODROID systemd[1]: jottad.service: Failed with result 'exit-code'.
Feb 20 23:07:15 VEBODROID systemd[1]: jottad.service: Scheduled restart job, restart counter is at 5.
Feb 20 23:07:15 VEBODROID systemd[1]: Stopped Jottacloud cli.
Feb 20 23:07:15 VEBODROID systemd[1]: jottad.service: Start request repeated too quickly.
Feb 20 23:07:15 VEBODROID systemd[1]: jottad.service: Failed with result 'exit-code'.
Feb 20 23:07:15 VEBODROID systemd[1]: Failed to start Jottacloud cli.

```

**Additional info:**
No other listeners on 14443

**Comment by Kimbsen** [comment]
Thanks for the report!

**Comment by Kimbsen** [comment]
We just released version 0.9.40946 on unstable which should fix this if we understand the problem correctly. 

Could you test that release? Info on how to switch to unstable is [here](https://github.com/jotta/jotta-cli-issues#stable-vs-unstable)

**Comment by seborama** [comment]
I believe this is still an issue.

system: raspberry pi 4 (ARM)

`jotta-cli version 0.10.43844`

upon running a `add`, such as `jotta-cli add ./backup/`
`jottad` crashes:
```
pid:6479 2021/05/12 19:51:47 Starting /usr/bin/jottad version 0.10.43844 as 0(root)/0 (linux:arm)
pid:6479 2021/05/12 19:51:47 jottad.init
pid:6479 2021/05/12 19:51:47 jottad.init.appdata => /var/lib/jottad
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/.ignore (1620841851|490)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/cldb (1620841852|16384)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/db (1620845381|32768)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/downloads
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/downloads/history (1620841852|16384)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/jottabackup.log (1620845507|39999)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/localfiles (1620845381|32768)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/nstore - (2cc1f5477d650634b639d94627666553|1620842338|65536)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/obj
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/obj/5b296082 (1620845381|806)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/settings.dat (1620845381|213)
pid:6479 2021/05/12 19:51:47 Loading settings from /var/lib/jottad/settings.dat
pid:6479 2021/05/12 19:51:48 jottad.init.cfg.downloadrate => 0B/s
pid:6479 2021/05/12 19:51:48 jottad.init.cfg.uploadrate => 0B/s
pid:6479 2021/05/12 19:51:48 jottad.init.user => [609c1707fddc71013497e8c6] on [pi4] @ [9a7786702708e94f0cc8361a9c40adcd]
pid:6479 2021/05/12 19:51:48 jottad.init.cfg.scaninterval =>  1h0m0s
pid:6479 2021/05/12 19:51:48 jottad.init.done => ok
pid:6479 2021/05/12 19:51:48 jottad.startup
pid:6479 2021/05/12 19:51:48 api.grpc.tls.active => 127.0.0.1:14443
pid:6479 2021/05/12 19:51:48 jottad.startup.update-userinfo => jottacloud@albion.onl Jottacloud 9a7786702708e94f0cc8361a9c40adcd
pid:6479 2021/05/12 19:51:48 jottad.startup.confirm-remote => ok
pid:6479 2021/05/12 19:51:48 jottad.startup => ok
pid:6479 2021/05/12 19:51:48 running 4 delayed startup tasks
pid:6479 2021/05/12 19:51:49 GET https://repo.jotta.us/archives/VERSION 200


pid:6479 2021/05/12 19:51:57 ok stat with 0 got filesystem info id[1105409cbfc1df5c] type[ext2/ext3] for path /jottad/backup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e34]

goroutine 26 [running]:
runtime/internal/atomic.goXadd64(0x3416014, 0x1, 0x0, 0x6, 0x308a580)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).nextid(...)
	/builds/jotta/desktop/client/exe/jottad/daemon/daemon.go:1175
git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).handleAddBackupRequest(0x3416000, 0x31b3da0, 0x1c, 0x0, 0x0, 0x0, 0x33c5f40, 0x5ec5fa4, 0x0)
	/builds/jotta/desktop/client/exe/jottad/daemon/addbackup.go:100 +0x4f8
git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).loop(0x3416000)
	/builds/jotta/desktop/client/exe/jottad/daemon/daemon.go:1100 +0xc8c
created by git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).Start
	/builds/jotta/desktop/client/exe/jottad/daemon/daemon.go:789 +0xe4
```

**Comment by seborama** [comment]
I believe this is still an issue.

system: raspberry pi 4 (ARM)

`jotta-cli version 0.10.43844`

upon running a `add`, such as `jotta-cli add ./backup/`
`jottad` crashes:
```
pid:6479 2021/05/12 19:51:47 Starting /usr/bin/jottad version 0.10.43844 as 0(root)/0 (linux:arm)
pid:6479 2021/05/12 19:51:47 jottad.init
pid:6479 2021/05/12 19:51:47 jottad.init.appdata => /var/lib/jottad
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/.ignore (1620841851|490)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/cldb (1620841852|16384)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/db (1620845381|32768)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/downloads
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/downloads/history (1620841852|16384)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/jottabackup.log (1620845507|39999)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/localfiles (1620845381|32768)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/nstore - (2cc1f5477d650634b639d94627666553|1620842338|65536)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/obj
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/obj/5b296082 (1620845381|806)
pid:6479 2021/05/12 19:51:47 jottad.appdata	/var/lib/jottad/settings.dat (1620845381|213)
pid:6479 2021/05/12 19:51:47 Loading settings from /var/lib/jottad/settings.dat
pid:6479 2021/05/12 19:51:48 jottad.init.cfg.downloadrate => 0B/s
pid:6479 2021/05/12 19:51:48 jottad.init.cfg.uploadrate => 0B/s
pid:6479 2021/05/12 19:51:48 jottad.init.user => [9a2745372708e941236326142740a829] on [pi4] @ [9a2745372708e941236326142740a829]
pid:6479 2021/05/12 19:51:48 jottad.init.cfg.scaninterval =>  1h0m0s
pid:6479 2021/05/12 19:51:48 jottad.init.done => ok
pid:6479 2021/05/12 19:51:48 jottad.startup
pid:6479 2021/05/12 19:51:48 api.grpc.tls.active => 127.0.0.1:14443
pid:6479 2021/05/12 19:51:48 jottad.startup.update-userinfo => user@example.com Jottacloud 9a2745372708e941236326142740a829
pid:6479 2021/05/12 19:51:48 jottad.startup.confirm-remote => ok
pid:6479 2021/05/12 19:51:48 jottad.startup => ok
pid:6479 2021/05/12 19:51:48 running 4 delayed startup tasks
pid:6479 2021/05/12 19:51:49 GET https://repo.jotta.us/archives/VERSION 200


pid:6479 2021/05/12 19:51:57 ok stat with 0 got filesystem info id[1105409cbfc1df5c] type[ext2/ext3] for path /jottad/backup
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11e34]

goroutine 26 [running]:
runtime/internal/atomic.goXadd64(0x3416014, 0x1, 0x0, 0x6, 0x308a580)
	/usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).nextid(...)
	/builds/jotta/desktop/client/exe/jottad/daemon/daemon.go:1175
git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).handleAddBackupRequest(0x3416000, 0x31b3da0, 0x1c, 0x0, 0x0, 0x0, 0x33c5f40, 0x5ec5fa4, 0x0)
	/builds/jotta/desktop/client/exe/jottad/daemon/addbackup.go:100 +0x4f8
git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).loop(0x3416000)
	/builds/jotta/desktop/client/exe/jottad/daemon/daemon.go:1100 +0xc8c
created by git.jotta.us/jotta/desktop/client/exe/jottad/daemon.(*Daemon).Start
	/builds/jotta/desktop/client/exe/jottad/daemon/daemon.go:789 +0xe4
```

**Comment by Raspbianuser** [comment]
`Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?`

**Comment by seborama** [comment]
> `Error: Could not connect to jottad. Is it running on 127.0.0.1:14443 ?`
> 

The stack trace answers that:
Jottad crashed which prevented jotta-cli from continuing.

**Comment by seborama** [comment]
The latest update from yesterday has resolved the crash.
Thanks!
