### ISSUE TITLE
Can't backup NFS-mounted filesystem

### ISSUE THREAD

**Issue by rkarlsba** [jotta/jotta-cli-issues#7]
**jotta-cli release (`jotta-cli version`):**
0.3.4195

**Description of problem:**
I have a machine with some disks, and I try to separate services as good as possible to increase system security and stability. Now, jottad runs as root, meaning if a bad bug or security breach can be disasterous. So I've setup a small virtual machine to do the job. To this VM, I have exported the data filesystem read-only and no_root_squash, meaning root can read everything on it, but never write. Now jotta-clli refuses to add NFS-mounted filesystem:

# jotta-cli add /somefs
Error: [2] Could not add path to backup: Unsupported filesystem [NFS_SUPER_MAGIC] for key [0x6969]

**Expected:**
That it works…

**jotta-cli status (`jotta-cli status`):**
```
Nothing relevant
```

**Relevant logs for the issue (`cat ~/.jottad/jottabackup.log`)**
```
Nothing in the logs
```

**Traceback**
```
Nada
```

**Additional info:**

**Comment by rkarlsba** [comment]
As far as I can see, jottad doesn't like other networked filesystems either, FUSE included. This must be intentional, since an strace of jottad clearly shows statfs() being called to check the fstype. NFS is posix-compliant and it should be no problem backing it up, technically, since the system calls are the same all over and you won't even know it's NFS unless you look closely (with statfs()).

Running a closed-source daemon with access to the internet as root on the host system is a security hole the size jupiter or something of a similar size. It doesn't take more than a small bug and *boom* there went your server, and backup, and all, in one go. Please see #10 too.

**Comment by rolandrabben** [comment]
There are currently multiple of file systems we do not support. Both local and network filesystems. NFS and FUSE are not supported. 

I would suggest installing the tool on the host where the data is located. The tool supports many plattforms.

If you are worried about root access, simply run the jottad daemon as a different user. It does not require root access. You might need to modify the init script. We will add some docs on how to do that.

**Comment by rkarlsba** [comment]
Can you please remove these ban lists of filesystems, at least if the sysadmin (me) adds some option to jottad (for instance --yes-i-know-what-i-am-doing-for-gods-sake)? It really doesn't make sense to block certain filesystems unless you want to annoy your customers.

**Comment by evenwebb** [comment]
I agree, I am trying to run the CLI in Docker as I have all my software running in docker on the UnRaid operating system. But Docker mapped folders, even ones that link to files on the same system as the docker container (Which is what I'm trying to do) show this error and are "un-supported". UnRaid is a modified and stripped OS that does not generally support installing applications natively, at the moment its looking like I have to run a whole VM JUST to run the Docker client, when there are already docker images for all of your competition. I was looking to swap to you from Crashplan, but your not making it so easy.

Please could you explain your reasoning behind your decision to disallow those file systems?

**Comment by rkarlsba** [comment]
It is quite obvious that there isn't a stability issue here - if it were, we would be given a beta that allowed this, and then, everything we're talking about is posix, after all.

**Comment by evenwebb** [comment]
There is also very little third party client support, I wonder if its because they are trying to keep away users that are more likely to have vast amounts of data. Just a thought.

**Comment by rkarlsba** [comment]
There is duplicati, which can use jotta as a backend. There's jottalib, which hasn't been worked on for some time. This filesystem ban (and path ban on /var) is really annoying, and I haven't found a good workaround yet, and I suspect if I do, they'll ban me for doing so. They're promoting "free storage", but could have said "until <x>TB" to avoid service abuse. They could have opened the API or even the client, which shouldn't be a problem so far as their internal systems are secured. They don't.

**Comment by evenwebb** [comment]
I have Duplicati setup, but I was wanting to upload my files 1:1 and be able to access them from any device. For example, my iTunes music to: Archive/iTunes, my Photos directly to the Photos section od Jottacloud etc. You cant even do that with the windows app.

They have said on Reddit that they have users using around 40TB, and they are happy with that. They used to have a 10TB limit to their "unlimited plan" but that has been officially confirmed as no longer applicable.

**Comment by rkarlsba** [comment]
Yeah, they had a 10TB limit, but someone complained to the Norwegian Consumer Ombudsman and they removed it.

**Comment by evenwebb** [comment]
Oh ok, didn’t realise it went that far. 

I love the different sections on the web UI, the ability to archive files from the sync folder and the computer backup section. I really want to love the service but it’s not so easy to work into my workflow with the limited client access. 

I don’t understand why/how it’s been integrated into Duplicati but no other software.

**Comment by torarnv** [comment]
I plan on using `jotta-cli`:
- In a Docker container
- Backing up data from a `gocryptfs --reverse` mount (FUSE)

As I understand it this is not possible with  `jotta-cli`, for unknown reasons. 

@rolandrabben can you confirm this? Can you elaborate on why you don't support it?

**Comment by rkarlsba** [comment]
Do you (jotta) have an update on supporting other filesystems? As you can see from the bugs reported here, a large number of them concerns the same as reported here.

**Comment by rkarlsba** [comment]
Any updates on this? I saw the package was updated frequently, but then, nothing new for some weeks now.

**Comment by rolandrabben** [comment]
We will add experimental support for adding network mounted file systems and paths that contain subfolders that are network mounted.

If you add a path that is network mounted, you will get a warning, and the option to cancel or allow.

Our main concern for restricting this has been:

- If a network mounted folder is unmounted, the client might interpret that as if the folder has been deleted, end will then move the folder to the trash can on Jottacloud.

- We are not able to test all the different file systems out, and there might be issues with different file systems that can cause different problems. Even though they are POSIX.

Letting users add these filesystems on their own risk will now be possible. 

I expect the release to be out some time next week.

**Comment by torarnv** [comment]
Thanks @rolandrabben !

**Comment by Goredon** [comment]
Hello,

I have another problem: I tried to avoid the NFS-sync problem by copying all data to al local drive on my raspi:

mount
/dev/mmcblk0p2 on / type f2fs 
/dev/sda1 on /media/disk type ext4

when I try to add a folder of the ext4-Disk I get:
jotta-cli add /media/disk/Musik/
Error: [2] Unknown filesystem [0x-d0adff0]

**Comment by evenwebb** [comment]
Thank you very much @rolandrabben 😃

**Comment by mabahj** [comment]
Any update on this? I got "Error: [2] Could not add path to backup: Unknown filesystem [0xfe534d42] key [4266872130] " when I tried to add an SMB file system, so I'd assume it is the same restriction?

This is really unfortunate for me. I just bough and installed a Synology NAS and moved the disks over. But now I cannot back it up. My Synology version (DS418j) does not support any VMs either. Anyone that knows a workaround?

**Comment by mabahj** [comment]
The file system I'm trying to mount (when Jotta responds "Unknown filesystem" and exits) is of type cifs. Ubuntu 18.04.1 LTS,  jotta-cli version 0.4.4986.

(Please let me know if I should open a new ticket, but this seems directly related to Roland's comment "We will add experimental support for adding network mounted file systems and paths that contain subfolders that are network mounted.")

**Comment by Kimbsen** [comment]
This should be resolved with the 0.5 release.

**Comment by JacopKane** [comment]
I'm still not allowed to add some paths in macOS. GUI works fine, but `jotta-cli` refuses to add FUSE mounts.

I managed to work around this by mounting FUSE with `local` option, then probably you can remove it afterwards.

It's quite ugly and dangerous to data though, hope at least there would be a `--force` flag or similar in future for the people that know what they are doing.
